"""forecast store

Revision ID: 6bb39d32ff80
Revises: 885b4fa91ba5
Create Date: 2026-10-01 18:33:34.100242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bb39d32ff80'
down_revision: Union[str, Sequence[str], None] = '885b4fa91ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=False),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('best_model', sa.String(length=32), nullable=True),
    sa.Column('selection_metric', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mape_status', sa.String(length=32), nullable=False),
    sa.Column('interval_type', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('train_from', sa.String(length=32), nullable=False),
    sa.Column('train_to', sa.String(length=32), nullable=False),
    sa.Column('val_from', sa.String(length=32), nullable=False),
    sa.Column('val_to', sa.String(length=32), nullable=False),
    sa.Column('duration_s', sa.Double(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['forecast_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('actual', sa.Double(), nullable=True),
    sa.Column('predicted', sa.Double(), nullable=True),
    sa.Column('lower', sa.Double(), nullable=True),
    sa.Column('upper', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_points')
    op.drop_table('forecast_runs')
    op.drop_table('forecast_groups')
    # ### end Alembic commands ###
