"""analytical marts

Revision ID: 885b4fa91ba5
Revises: 5854c749f1d8
Create Date: 2026-09-30 20:10:54.741904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885b4fa91ba5'
down_revision: Union[str, Sequence[str], None] = '5854c749f1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_daily',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'date', 'country')
    )
    op.create_table('customer_summary',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'customer_id')
    )
    op.create_table('product_daily',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stockcode', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'date', 'stockcode')
    )
    op.create_table('product_summary',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('stockcode', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'stockcode')
    )
    op.create_table('sales_daily',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'date')
    )
    op.create_table('sales_monthly',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('revenue', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_monthly')
    op.drop_table('sales_daily')
    op.drop_table('product_summary')
    op.drop_table('product_daily')
    op.drop_table('customer_summary')
    op.drop_table('country_daily')
    # ### end Alembic commands ###
