"""anomaly store

Revision ID: bef5774bd309
Revises: 6bb39d32ff80
Create Date: 2026-10-01 21:06:51.459531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef5774bd309'
down_revision: Union[str, Sequence[str], None] = '6bb39d32ff80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=16), nullable=False),
    sa.Column('dim_key', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('observed', sa.Double(), nullable=False),
    sa.Column('expected', sa.Double(), nullable=False),
    sa.Column('deviation', sa.Double(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalies')
    # ### end Alembic commands ###
